spring.application.name=StudentManagment

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/springdb}
spring.datasource.username=${JDBC_DATABASE_USERNAME:arun}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:arun}
spring.jpa.hibernate.ddl-auto=update
