spring.application.name=StudentManagment

spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=arun
spring.datasource.password=arun
spring.jpa.hibernate.ddl-auto=update
